# These are supported funding model platforms

# github: [your_github_username]  # GitHub Sponsors
# buy_me_a_coffee: your_username
# ko_fi: your_username
# patreon: your_username
custom: ["https://etherscan.io/address/0xD76f061DaEcfC3ddaD7902A8Ff7c47FC68b3Dc49"]
